export const bucket = [
    { name: 'Apple', isFruit: true, id: 1 },
    { name: 'Banana', isFruit: true, id: 2 },
    { name: 'Potato', isFruit: false, id: 3 },
    { name: 'Kiwi', isFruit: true, id: 4 },
    { name: 'Cabbage', isFruit: false, id: 5 },
    { name: 'Garlic', isFruit: false, id: 6 },
    { name: 'Orange', isFruit: true, id: 7 },
    { name: 'Pear', isFruit: true, id: 8 },
    { name: 'Tomato', isFruit: true, id: 9 },
    { name: 'Carrot', isFruit: false, id: 10 },
    { name: 'Pineapple', isFruit: true, id: 11 },
    { name: 'Onion', isFruit: false, id: 12 },
    { name: 'Strawberry', isFruit: true, id: 13 },
    { name: 'Lettuce', isFruit: false, id: 14 },
    { name: 'Watermelon', isFruit: true, id: 15 },
    { name: 'Grapes', isFruit: true, id: 16 },
    { name: 'Mango', isFruit: true, id: 17 },
    { name: 'Blueberry', isFruit: true, id: 18 },
    { name: 'Eggplant', isFruit: false, id: 19 },
    { name: 'Peach', isFruit: true, id: 20 },
    { name: 'Cherry', isFruit: true, id: 21 },
    { name: 'Bell Pepper', isFruit: false, id: 22 },
    { name: 'Raspberry', isFruit: true, id: 23 },
    { name: 'Avocado', isFruit: true, id: 24 },
    { name: 'Zucchini', isFruit: false, id: 25 },
  ];
  